// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index').default>>>>
    }
    '/v1/agents': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/agents/index').default>>>>
    }
    '/v1/analytics': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/analytics/index').default>>>>
    }
    '/v1/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/auth/index').default>>>>
    }
    '/v1/conversations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/conversations/index').default>>>>
    }
    '/v1/customers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/customers/index').default>>>>
    }
    '/v1/documents': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/documents/index').default>>>>
    }
    '/v1/embeddings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/embeddings/index').default>>>>
    }
    '/v1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/index').default>>>>
    }
    '/v1/invitations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/invitations/index').default>>>>
    }
    '/v1/message-feedback': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/message-feedback/index').default>>>>
    }
    '/v1/onboarding': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/onboarding/index').default>>>>
    }
    '/v1/organizations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/organizations/index').default>>>>
    }
    '/v1/playbooks': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/playbooks/index').default>>>>
    }
    '/v1/plugins': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/plugins/index').default>>>>
    }
    '/v1/plugins/plugins.handler': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/plugins/plugins.handler').default>>>>
    }
    '/v1/public-conversations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/public-conversations/index').default>>>>
    }
    '/v1/sources': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/sources/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}