name: hay-platform
region: nyc
features:
  - buildpack-stack=ubuntu-22

services:
  - name: backend
    github:
      repo: your-github-repo
      branch: main
      deploy_on_push: true
    build_command: |
      npm ci --include=dev
      cd dashboard && npm ci --include=dev && cd ..
      cd server && npm ci --include=dev && cd ..
      npm run build:dashboard
      npm run build:server
    run_command: UNIFIED_MODE=true NODE_ENV=production cd server && node start-production.js
    envs:
      - key: NODE_ENV
        value: production
      - key: UNIFIED_MODE
        value: "true"
      - key: PORT
        value: "8080"
      - key: DB_HOST
        scope: RUN_TIME
        type: SECRET
      - key: DB_PORT
        scope: RUN_TIME
        type: SECRET
      - key: DB_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /