import { t } from "@server/trpc";
import {
  getAllPlugins,
  getPlugin,
  getPluginInstances,
  enablePlugin,
  disablePlugin,
  configurePlugin,
  getPluginConfiguration,
  getPluginUITemplate,
  getMCPTools,
  refreshMCPTools,
  getMenuItems,
  testConnection,
  initiateOAuth,
  isOAuthAvailable,
  getOAuthStatus,
  revokeOAuth,
  validateAuth,
} from "./plugins.handler";

export const pluginsRouter = t.router({
  getAll: getAllPlugins,
  get: getPlugin,
  getInstances: getPluginInstances,
  enable: enablePlugin,
  disable: disablePlugin,
  configure: configurePlugin,
  getConfiguration: getPluginConfiguration,
  getUITemplate: getPluginUITemplate,
  getMCPTools: getMCPTools,
  refreshMCPTools: refreshMCPTools,
  getMenuItems: getMenuItems,
  testConnection: testConnection,
  validateAuth: validateAuth,
  oauth: {
    initiate: initiateOAuth,
    isAvailable: isOAuthAvailable,
    status: getOAuthStatus,
    revoke: revokeOAuth,
  },
});
